apiVersion: v2
name: mes-pipeline
description: MES Streaming Pipeline (Kappa-Architektur) auf Kubernetes - Kafka, Spark Structured Streaming, MinIO, FastAPI, Dash
type: application
version: 0.2.0
appVersion: "0.1"
