apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials-example-do-not-apply
  namespace: mes
type: Opaque
stringData:
  MINIO_ROOT_USER: "PLATZHALTER-BENUTZER"
  MINIO_ROOT_PASSWORD: "PLATZHALTER-PASSWORT"
  MINIO_ACCESS_KEY: "PLATZHALTER-BENUTZER"
  MINIO_SECRET_KEY: "PLATZHALTER-PASSWORT"

##### kubectl command to store secret
# kubectl apply -f k8s/config/11-secret.yaml