apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials-EXAMPLE-DO-NOT-APPLY
  namespace: mes
type: Opaque
stringData:
  MINIO_ROOT_USER: "PLATZHALTER-BENUTZER"
  MINIO_ROOT_PASSWORD: "PLATZHALTER-PASSWORT"
  MINIO_ACCESS_KEY: "PLATZHALTER-BENUTZER"
  MINIO_SECRET_KEY: "PLATZHALTER-PASSWORT"

##### kubectl command to store secret
# kubectl create secret generic minio-credentials -n mes \
# --from-literal=MINIO_ROOT_USER=mesadmin \
# --from-literal=MINIO_ROOT_PASSWORD='EinStarkesPasswort!42' \
# --from-literal=MINIO_ACCESS_KEY=mesadmin \
# --from-literal=MINIO_SECRET_KEY='EinStarkesPasswort!42'