apiVersion: v1
kind: Service
metadata:
  name: stream-processing-driver
spec:
  clusterIP: None          # kein Lastausgleich: es gibt genau einen Driver
  selector:
    app: stream-processing
  ports:
    - name: driver-rpc
      port: 7078
    - name: driver-blockmanager
      port: 7079