apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.auth.rootPassword | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.rootPassword | quote }}