apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: mes
  labels:
    app: ui
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - name: http
      port: 8050
      targetPort: 80
      nodePort: 30080