apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-api
  namespace: mes
  labels:
    app: serving-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving-api
  template:
    metadata:
      labels:
        app: serving-api
    spec:
      containers:
        - name: serving-api
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /     # aaron api ready path
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /     # aaron api live path (health)
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
