apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: serving-api
  namespace: mes
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serving-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 300
